clc;

NUM_POINTS = 100;
RIGHT_ENDPOINT = 0.1;
SAMPLES = 100;
RESULT_FILE = "simulationData";

USE_CUSTOM_SET = false;
CUSTOM_SET_FILE = "";

simulateDeviation(NUM_POINTS, RIGHT_ENDPOINT, SAMPLES, RESULT_FILE, USE_CUSTOM_SET, CUSTOM_SET_FILE);